name: wp3-solutions 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh
          ./code-coverage.sh

      - name: Deploy Jacoco code coverage reports to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ matrix.java-version == '15.0.x' && github.ref == 'refs/heads/master' }}
        with:
          clean: true
          folder: jacoco
          target-folder: reports
          branch: gh-pages

