name: wp3-solutions 

on:
  push:
    branches:
      - testing-dockerhub-push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql

  docker:

    needs: build
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          architecture: x64
      -
        name: Prepare Dockerfiles and files for Contexts
        run: |
          ./build-for-docker.sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
