name: wp3-solutions 

on:
  push:
    branches:
      - master

jobs:

  # Build and test the applications with multiple Java versions
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql
          ./code-coverage.sh

      - name: Generate Jacoco Badge (EDHOC)
        id: jacoco-edhoc
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/edhoc/jacoco.csv
          coverage-badge-filename: jacoco-edhoc.svg
          coverage-label: EDHOC

      - name: Generate Jacoco Badge (OSCORE & Group OSCORE)
        id: jacoco-oscore
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/oscore/jacoco.csv
          coverage-badge-filename: jacoco-oscore.svg
          coverage-label: OSCORE & Group OSCORE

      - name: Generate Jacoco Badge (ACE & Group Joining)
        id: jacoco-ace
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/ace/jacoco.csv
          coverage-badge-filename: jacoco-ace.svg
          coverage-label: ACE & Group Joining

      - name: Move the badges to jacoco folder
        run: |
          mv .github/badges/*.svg jacoco/

      - name: Deploy Jacoco code coverage reports to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ matrix.java-version == '8.0.x' }}
        with:
          clean: true
          folder: jacoco
          target-folder: reports
          branch: gh-pages

  
  # Build files neccessary for building of Docker Images (Dockerfiles and Contexts)
  build-for-docker:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 8.0.x
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'
          
      - name: Prepare Dockerfiles and files for Contexts
        run: |
          ./build-for-docker.sh
             
      - name: Upload artifacts for Docker Image building
        uses: actions/upload-artifact@v3
        with:
          name: files-for-docker
          retention-days: 5
          if-no-files-found: error
          path: |
            ./*/group/*
            ./*/edhoc/*
            ./*/group/lib/*
            ./*/edhoc/lib/*
  

  # Build multiarch Docker Images and push as Github Packages
  docker-image-push:

    if: ${{ github.repository == 'sifis-home/wp3-solutions' }}
    needs: [build-and-test, build-for-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts for Docker Image building
        uses: actions/download-artifact@v3
        with:
          name: files-for-docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (Authorization Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/authorization-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - ACE Authorization Server

      - name: Build and push image (Group Manager)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreRsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-manager:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group Manager (ACE Resource Server)

      - name: Build and push image (Group Adversary)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-Adversary
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-adversary:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group Adversary

      - name: Build and push image (Group OSCORE Client 1)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Client1
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-client1:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Client 1 (Group A)

      - name: Build and push image (Group OSCORE Client 2)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Client2
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-client2:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Client 2 (Group B)

      - name: Build and push image (Group OSCORE Server 1)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server1
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server1:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 1 (Group A)

      - name: Build and push image (Group OSCORE Server 2)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server2
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server2:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 2 (Group A)

      - name: Build and push image (Group OSCORE Server 3)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server3
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server3:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 3 (Group A)

      - name: Build and push image (Group OSCORE Server 4)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server4
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server4:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 4 (Group B)

      - name: Build and push image (Group OSCORE Server 5)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server5
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server5:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 5 (Group B)

      - name: Build and push image (Group OSCORE Server 6)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server6
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server6:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Group OSCORE Server 6 (Group B)

      - name: Build and push image (CoAP Phase0Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase0Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase0-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase0Client (CoAP-only Client)

      - name: Build and push image (EDHOC Phase1Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase1Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase1-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase1Server (EDHOC server using method 0 and no optimized request)

      - name: Build and push image (EDHOC Phase1Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase1Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase1-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase1Client (EDHOC client using method 0 and no optimized request)

      - name: Build and push image (EDHOC Phase2Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase2Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase2-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase2Server (EDHOC server using method 3 and no optimized request)

      - name: Build and push image (EDHOC Phase2Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase2Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase2-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase2Client (EDHOC client using method 3 and no optimized request)

      - name: Build and push image (EDHOC Phase3Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase3Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase3-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase3Server (EDHOC server using method 0 and the optimized request)

      - name: Build and push image (EDHOC Phase3Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase3Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase3-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase3Client (EDHOC client using method 0 and the optimized request)

      - name: Build and push image (EDHOC Phase4Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase4-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase4Server (EDHOC server using method 3 and the optimized request)

      - name: Build and push image (EDHOC Phase4Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/phase4-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions - Phase4Client (EDHOC client using method 3 and the optimized request)

