name: wp3-solutions 

on:
  push:
    branches:
      - test2

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
     
      - uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          architecture: x64
     
      - name: Build Jar files and prepare dependencies for applications
        run: |
          ./build-group-apps.sh
          ./build-edhoc-apps.sh

