name: wp3-solutions 

on:
  push:
    branches:
      - as-logging-wip

jobs:

  # Build and test the applications with multiple Java versions
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: 'zulu'

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql
          ./code-coverage.sh
  
  # Build files neccessary for building of Docker Images
  build-for-docker:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8.0.x
          architecture: x64
          distribution: 'zulu'
          
      - name: Prepare Dockerfiles and files for Contexts
        run: |
          ./build-for-docker.sh
             
      - name: Upload artifacts for Docker Image building
        uses: actions/upload-artifact@v3
        with:
          name: files-for-docker
          retention-days: 5
          if-no-files-found: error
          path: |
            ./*/group/*
            ./*/edhoc/*
            ./*/group/lib/*
            ./*/edhoc/lib/*
  

  # Build multiarch Docker Images and push as Github Packages
  docker:

    if: ${{ github.repository == 'sifis-home/wp3-solutions' }}
    needs: [build-and-test, build-for-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts for Docker Image building
        uses: actions/download-artifact@v3
        with:
          name: files-for-docker
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub container registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push image (Authorization Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/authorization-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Authorization Server
      
      - name: Build and push image (Group Manager)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreRsServer
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-manager:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Group Manager
      
      - name: Build and push image (Group OSCORE Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Client2
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Group OSCORE Client
      
      - name: Build and push image (Group OSCORE Server 1)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server4
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server1:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Group OSCORE Server 1
      
      - name: Build and push image (Group OSCORE Server 2)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server5
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server2:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Group OSCORE Server 2
      
      - name: Build and push image (Group OSCORE Server 3)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/group/.
          file: docker-build/group/Dockerfile-OscoreAsRsClient-Server6
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/group-server3:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions Group OSCORE Server 3
      
      - name: Build and push image (CoAP Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase0Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/coap-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions CoAP Server
      
      - name: Build and push image (CoAP Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase0Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/coap-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions CoAP Client
      
      - name: Build and push image (EDHOC Server)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Server
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/edhoc-server:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions EDHOC Server
      
      - name: Build and push image (EDHOC Client)
        uses: docker/build-push-action@v4
        with:
          context: docker-build/edhoc/.
          file: docker-build/edhoc/Dockerfile-Phase4Client
          platforms: linux/amd64, linux/arm64, linux/arm
          push: true
          tags: ghcr.io/sifis-home/edhoc-client:latest
          outputs: type=registry, annotation-index.org.opencontainers.image.description=wp3-solutions EDHOC Client

